### PR TITLE
Update maven repository information

### PR DESCRIPTION
**Pull request by phinner**

### CODE REVIEW

**Comment by Xasmedy** [comment]
Is it not strange that the API keeps being available on a repository not managed by us?

**Comment by phinner** [comment]
> Is it not strange that the API keeps being available on a repository not managed by us?

Unless you have your own maven repository, I don't see a problem with that.

**Comment by Xasmedy** [comment]
The only problem is that we can not manage the distribution it in any way, and having someone else do it for us might not be the best option.

**Comment by phinner** [comment]
> The only problem is that we can not manage the distribution it in any way, and having someone else do it for us might not be the best option.

Isn't it the same for maven central ? You trust Sonatype with the hosting of the artifacts.

Frankly I don't understand why you suddenly see a problem with me, hosting a simple maven repository for **you** for **free** with **nothing in return**. I also host artifacts for other servers like Omega, and they don't complain like this.

If you really want to host that yourself that badly, just create your own maven repo like I mentioned earlier and I will gladly send you the file-store artifacts.

**Comment by phinner** [comment]
I managed to redirect the URL to the new repository with nginx black magik.

**Pull request closed without merging**
